# Generated by Django 5.1.7 on 2025-12-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oqituvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('guruhlar_soni', models.IntegerField()),
                ('oqituvchilar_miqdori', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('guruhlar_soni', models.IntegerField()),
            ],
        ),
    ]
