# Generated by Django 5.1.7 on 2025-12-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OqituvchiTahrirlash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('tugilgan_sana', models.DateField()),
                ('jinsi', models.CharField(choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='oqituvchilar/')),
                ('parol', models.CharField(max_length=128)),
            ],
        ),
    ]
