# Generated by Django 5.1.7 on 2025-12-15 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_oqituvchitahrirlash'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(max_length=13)),
                ('rollari', models.CharField(max_length=100)),
                ('filliallari', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qaysi_kursligi', models.CharField(max_length=100)),
                ('boshlash_sanasi', models.DateField()),
                ('tugash_sanasi', models.DateField()),
                ('toq_kunlar', models.CharField(max_length=50)),
                ('first_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guruhlar', to='api.firstteacher')),
            ],
        ),
        migrations.CreateModel(
            name='OqituvchiSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_matni', models.TextField()),
                ('oqituvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smslar', to='api.oqituvchi')),
            ],
        ),
    ]
